config/routes.rb
Rails.application.routes.draw do

  devise_for :vendors, controllers: { registrations: 'registrations' }
  namespace :api, defaults: {format: 'json'} do
    resources :sites
  end

  resources :sites
  resources :requests
  resources :vendors

  root to: 'sites#index'

end

app/models/request.rb
class Request < ActiveRecord::Base
    belongs_to :site

    validates :customer_name, length: {minimum: 3}
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  def index
    @sites = Site.all
  end

  def new
    @site = Site.find_by_id(session[:current_site_id])
    @request = Request.new
  end

  def create
    @site = Site.find_by_id(session[:current_site_id])
    @request = @site.requests.build(request_params)
    if @request.save
      flash[:notice] = "Thank you.  Your request has been made."
      redirect_to "/"
    else
      flash[:notice] = "Sorry. Request not processed due to incorrect information."
      redirect_to "/requests/new"
    end
  end

  def destroy
    @request = Request.find(params[:id])
    @request.destroy
    redirect_to '/requests'
  end

  def request_params
    params.require(:request).permit(:customer_name, :customer_email, :customer_phone, :start_date, :end_date, :comments)
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/index.html.erb
<nav class="navbar custom-navbar">
  <div class="container-fluid">
      <a class="navbar-brand" href="/">
          <img alt="Beyond camping" src="<%= image_url "Logo-darkgrey-sml.png" %>" class="bc-logo">
        </a>
      <ul class="navbar-right">
        <li class="b" style="list-style:none;"><%= button_to "Return", vendors_path, class: "custom-nav-link" %></li>
      </ul>
  </div>
</nav>
<div class="container">
  <div class="row">
    <div class="col-md-6 line">
      <div class="h-title">
        <h4>Requests</h4>
        <span class="h-underline"></span>
      </div>
    <% @sites.each do |site| %>
      <% if site.vendor_id == current_vendor.id %>
          <% if site.requests.any? %>
            <div id="left">
              <% site.requests.each do |request| %>
                <div class='cust_info'>
                  <div class="site_name"><%= site.name %></div>
                  <table class="requests_table">
                    <col width="150">
                    <col width="250">
                    <tr>
                      <td>Customer name:</td>
                      <td><%= request.customer_name %></td>
                    </tr>
                    <tr>
                      <td>Dates requested:</td>
                      <td><%= request.start_date.strftime('%e %B %Y') %> to <%= request.end_date.strftime('%e %B %Y') %></td>
                    </tr>
                    <tr>
                      <td>Phone number:</td>
                      <td><%= request.customer_phone %></td>
                    </tr>
                    <tr>
                      <td>Email:</td>
                      <td><%= request.customer_email %></td>
                    </tr>
                    <tr>
                      <td>Comments:</td>
                      <td><%= request.comments %></td>
                    </tr>
                    <tr class="blank_row">
                      <td colspan="2"></td>
                    </tr>
                  </table>

                  Confirm booking <input class="reset functions" type="checkbox" id="request_check" name="request" onclick="move_info($(this).parent())" value="booking" style="opacity:1">
                  <div class="functions delete"><%= button_to "Delete", request_path(request), method: :delete, :class => "solid-brd-btn" %></div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      <% end %>
  </div>

  <div class="col-md-6">
    <div class="h-title">
      <h4>Bookings</h4>
      <span class="h-underline"></span>
    </div>
      <div id="right">
        <div id="no-bookings">
          <p class="no-bookings">
            No current bookings
          </p>
        </div>
      </div>
  </div>

  <!-- <div class="return_button form-btn reset">
    <%= button_to "Return", vendors_path %>
  <div> -->
</div>
</div>

app/views/requests/new.html.erb
<nav class="navbar custom-navbar">
  <div class="container-fluid">
      <a class="navbar-brand" href="/">
          <img alt="Beyond camping" src="<%= image_url "Logo-darkgrey-sml.png" %>" class="bc-logo">
        </a>
      <ul class="navbar-right custom-nav-link">
        <li><%= link_to "List a site", '/vendors', class: "custom-nav-link" %></li>
      </ul>
  </div>
</nav>
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <div class="h-title">
        <h4>Booking Requests</h4>
        <span class="h-underline"></span>
      </div>

      <div class="custom-form">
      <%= form_for [@request] do |f| %>
        <div class="form-group">
          <%= f.label :name, class: "custom-label" %>
          <%= f.text_field :customer_name, autofocus: true, class: "form-control custom-input" %>
        </div>
        <div class="form-group">
          <%= f.label :email, class: "custom-label" %></p>
          <%= f.text_field :customer_email, autofocus: true, class: "form-control custom-input" %>
        </div>

        <div class="form-group">
          <%= f.label "Phone Number", class: "custom-label" %>
          <%= f.text_field :customer_phone, autofocus: true, class: "form-control custom-input" %>
        </div>

        <div class="form-group">
          <%= f.label "Start Date", class: "custom-label" %><br />
          <%= f.date_select(:start_date, order: [:day, :month, :year], :html => {:class => "form-control custom-select"}) %>
        </div>

        <div class="form-group">
          <%= f.label "End Date", class: "custom-label" %><br />
          <%= f.date_select(:end_date, order: [:day, :month, :year], :html => {:class => "form-control custom-select"}) %>
        </div>

        <div class="form-group">
          <%= f.label :comments, class: "custom-label" %>
          <%= f.text_field :comments, autofocus: true, class: "form-control custom-input textarea-tall" %>
        </div>

        <div class="form-group form-btn upload-btn sml-width">
          <%= f.submit %>
        </div>
      <% end %>

      <div class="devise-links b">
        <%= button_to "&#8592; Back".html_safe, site_path(@site), :method => "get" %>
      </div>
      </div>
    </div>
  </div>
</div>