config/routes.rb
Rails.application.routes.draw do

  devise_for :vendors, controllers: { registrations: 'registrations' }
  namespace :api, defaults: {format: 'json'} do
    resources :sites
  end

  resources :sites
  resources :requests
  resources :vendors

  root to: 'sites#index'

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :sites
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController

  def index
    @sites = Site.all
  end

  def show
    @site = Site.find(params[:id])
    # session[:current_site_id] = @site.id
  end

end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/index.html.erb
<nav class="navbar custom-navbar">
  <div class="container-fluid">
      <a class="navbar-brand" href="/">
          <img alt="Beyond camping" src="<%= image_url "Logo-darkgrey-sml.png" %>" class="bc-logo">
        </a>
      <ul class="navbar-right custom-nav-link">
        <li>
            <% if vendor_signed_in? %>
            <div class="devise-links devise-btn">
                <%= link_to "Log Out", destroy_vendor_session_path, method: :delete %>
            </div>
            <% else %>
            <div class="devise-links devise-btn">
              <%= link_to "Sign Up", new_vendor_registration_path %>
              <%= link_to "Log In", new_vendor_session_path %>
            </div>
            <% end %>
        </li>
      </ul>
  </div>
</nav>
<div class="container">
  <div class="row">
    <div class="h-title">
      <h4>Vendors</h4>
      <span class="h-underline"></span>
    </div>

  <% if vendor_signed_in? %>

    <div class="reset vendor_function"><%= link_to "List a new site", new_site_path %></div>
    <div class="reset vendor_function"><%= link_to "Booking Requests", requests_path %></div>
    <div>
    <% @sites.each do |site| %>
      <% if site.vendor_id == current_vendor.id %>
        <div class="vendor_sites">
          <%= site.name %>
          <p><%= link_to "Edit", edit_site_path(site) %>&nbsp;/&nbsp;
          <%= link_to "Delete", site_path(site), method: :delete %>&nbsp;/&nbsp;
          <%= link_to "Preview", vendor_path(site) %></p>
          </div>
      <% end %>
    <% end %>
  </div>
  <!-- <div class="devise-links b">
      <%= link_to "Log Out", destroy_vendor_session_path, method: :delete %>
  </div> -->
  <% end %>
  <div class="span12" >
    <div class="devise-links devise-btn">
      <%= link_to "&#8592; Return to list".html_safe, '/' %>
    </div>
  </div>
</div>
</div>

app/views/vendors/show.html.erb
<nav class="navbar custom-navbar">
  <div class="container-fluid">
      <a class="navbar-brand center" href="/">
        <img alt="Beyond camping" src="<%= image_url "Logo-darkgrey-sml.png" %>" class="bc-logo">
      </a>
  </div>
</nav>
<div class="container">
  <!-- <div class="row"> -->
    <div class="col-xs-10 col-xs-offset-1">
      <div class="h-title">
        <h4><%= @site.name %></h4>
        <span class="h-underline"></span>
      </div>
      <div class="row">
      <div class="photo-viewer" id="photo-viewer"></div>
        <div class="thumbnails" id="thumbnails">
          <a href='<%= @site.image.url(:large) %>' class='thumb active'>
            <img src="<%= @site.image.url(:thumb) %>" />
          </a>
          <a href='<%= @site.image_2.url(:large) %>' class='thumb active'>
            <img src="<%= @site.image_2.url(:thumb) %>" />
          </a>
          <a href='<%= @site.image_3.url(:large) %>' class='thumb active'>
            <img src="<%= @site.image_3.url(:thumb) %>" />
          </a>
          <a href='<%= @site.image_4.url(:large) %>' class='thumb active'>
            <img src="<%= @site.image_4.url(:thumb) %>" />
          </a>
          <a href='<%= @site.image_5.url(:large) %>' class='thumb active'>
            <img src="<%= @site.image_5.url(:thumb) %>" />
          </a>
          <a href='<%= @site.image_6.url(:large) %>' class='thumb active'>
            <img src="<%= @site.image_6.url(:thumb) %>" />
          </a>
        </div>
      </div>

      <div class="row site-listing">

        <div class="tabs tabs-style-linemove">
          <nav>
            <ul>
              <li><a href="#section-linemove-1" class="icon icon-home"><span>Overview</span></a></li>
              <li><a href="#section-linemove-2" class="icon icon-box"><span>Location</span></a></li>
              <li><a href="#section-linemove-3" class="icon icon-display"><span>Amenities</span></a></li>
              <li><a href="#section-linemove-4" class="icon icon-upload"><span>Leisure</span></a></li>
              <li><a href="#section-linemove-5" class="icon icon-tools"><span>Policies</span></a></li>
            </ul>
          </nav>
          <div class="content-wrap">
            <section id="section-linemove-1">
              <div class="align2">
              <p><span class="listing-bold">Accommodation Type:</span> <%= @site.accommodation_type %></p>
              <p><span class="listing-bold">Price per night:</span>  £<%= @site.price %></p>
              <p><span class="listing-bold">Max occupancy:</span> <%= @site.occupancy %></p>
              <p><span class="listing-bold">Description:</span>  <%= @site.description %></p>
              <p>
                <span class="listing-bold">Available from</span> <%= @site.available_from %> to <%= @site.available_to %>
              </p>
              </div>
            </section>

            <section id="section-linemove-2">
              <div class="align2">
              <div id="map" class="g-map"></div>
              <div class="site-address">
                <span class="listing-bold">Address:</span>
                <% [:street, :town, :county].each do |address_property| %>
                  <p class="no-pad"> <%= @site.send(address_property) %> </p>
                <% end %>
                <p id="postcode" class="no-pad"><%= @site.postcode %></p>
              </div>
              </div>
            </section>

            <section id="section-linemove-3">
              <div class="align3">
              <% Site.amenities.each do |amenity_name| %>
                <% amenity_exists = @site.send(amenity_name) ? "has" : "no" %>
                <p class='<%= amenity_exists %>-facility'>
                  <%= amenity_name.to_s.humanize %>
                </p>
              <% end %>
              </div>
            </section>
            <section id="section-linemove-4">
              <div class="align4">
              <% Site.leisure.each do |leisure_name| %>
                <% leisure_exists = @site.send(leisure_name) ? "has" : "no" %>
                <p class='<%= leisure_exists %>-facility'>
                  <%= leisure_name.to_s.humanize %>
                </p>
              <% end %>
              </div>
            </section>
            <section id="section-linemove-5">
              <div class="align5">
              <% Site.policies.each do |policy_name| %>
                <% policy_exists = @site.send(policy_name) ? "has" : "no" %>
                <p class='<%= policy_exists %>-facility'>
                  <%= policy_name.to_s.humanize %>
                </p>
              <% end %>
              </div>
            </section>
          </div>
        </div>

        <!-- <ul>
          Location Type:
          <% Site.locationtype.each do |locationtype_name| %>
            <% locationtype_exists = @site.send(locationtype_name) ? "has" : "no" %>
            <li class='<%= locationtype_exists %>-facility'>
                <%= locationtype_name.to_s.humanize %>
            </li>
          <% end %>
        </ul> -->

      </div>

      <div class="row">
        <div class="form-group green-btn sml-width sml-btn">
          <%= button_to "Booking enquiry", new_request_path, :method => "get" %>
        </div>
      </div>
<!-- <%= button_to "Back", sites_path, :method => "get" %> -->

    </div>

  <!-- </div> -->
</div>
<script>
	(function() {
		[].slice.call( document.querySelectorAll( '.tabs' ) ).forEach( function( el ) {
			new CBPFWTabs( el );
		});
	})();
</script>